core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("news.urls")),
    path("accounts/", include("allauth.urls")),
]

news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse


class Author(models.Model):
    name = models.OneToOneField(User, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)

    def update_rating(self):
        rat_post_all = 0
        rat_com_author = 0
        rat_com_all = 0
        for i in Post.objects.filter(author__name__username=self.name):
            rat_post_all += i.rating

        for i in Comment.objects.filter(user__username=self.name):
            rat_com_author += i.rating

        for post in Post.objects.filter(author__name__username=self.name):
            for i in Comment.objects.filter(post=post):
                rat_com_all += i.rating

        self.rating = rat_post_all * 3 + rat_com_author + rat_com_all
        self.save()

    def __str__(self):
        return f"{self.name}"


class Category(models.Model):
    name = models.CharField(max_length=120, unique=True)

    def __str__(self):
        return f"{self.name}"


class Subscriber(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    category = models.ManyToManyField(Category, through="SubscriberCategory")


class SubscriberCategory(models.Model):
    subscriber = models.ForeignKey(Subscriber, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Post(models.Model):
    news = "Новость"
    article = "Статья"
    type = [(news, "Новость"), (article, "Статья")]
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    type = models.CharField(max_length=30, choices=type, default=news)
    date_create = models.DateField(auto_now_add=True)
    category = models.ManyToManyField(
        "Category", through="PostCategory", verbose_name="Категории"
    )
    title = models.CharField(max_length=50)
    text = models.TextField()
    rating = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    dislikes = models.IntegerField(default=0)

    def get_absolute_url(self):
        if self.type == "Новость":
            return reverse("news_detail", args=[str(self.id)])
        elif self.type == "Статья":
            return reverse("article_detail", args=[str(self.id)])

    def __str__(self):
        return f"{self.title}"

    def preview(self):
        return self.text[:124] + "..."

    def like(self):
        self.likes += 1
        self.rating = self.likes - self.dislikes
        self.save()

    def dislike(self):
        self.dislikes += 1
        self.rating = self.likes - self.dislikes
        self.save()


class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.TextField()
    date_create = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    dislikes = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.text}"

    def like(self):
        self.likes += 1
        self.rating = self.likes - self.dislikes
        self.save()

    def dislike(self):
        self.dislikes += 1
        self.rating = self.likes - self.dislikes
        self.save()

templates/category_list.html
{% extends 'default.html' %}

{% block content %}

{% if object_list %}
<div class="container my-3">
    <div class="row row-cols-1 row-cols-md-2 g-3">
        {% for obj in object_list %}
        <div class="col">
            <div class="card h-100">
                <div class="row align-items-center m-2">
                    <div class="col">
                        <h5 class="">{{ obj.name }}</h5>
                        <a class="" href="#"></a>
                    </div>
                    <div class="col-auto">
                        <form action="{% url 'subscription' obj.pk %}" method="POST">
                            {% csrf_token %}
                            {{ form }}
                            {% if obj.name in is_subscriptions %}
                            <button type="submit" name="action" value="unsub"
                                class="btn btn-outline-dark">Отписаться</button>
                            {% else %}
                            <button type="submit" name="action" value="sub"
                                class="btn btn-outline-danger">Подписаться</button>
                            {% endif %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% else %}
<h4 class="text-center mt-3">Категорий нет</h4>
{% endif %}

{% endblock content %}

templates/default.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="stylesheet" href="{% static 'font/bootstrap-icons.css'%}" />
  <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" />
</head>

<body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary bg-light">
    <div class="container-fluid">
      <a class="navbar-brand text-dark" href="{% url 'post_list' %}">NewsPaper</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Переключатель навигации">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active text-dark" aria-current="page" href="{% url 'news_list' %}">Новости</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active text-dark" aria-current="page" href="{% url 'article_list' %}">Статьи</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active text-dark" aria-current="page" href="{% url 'search' %}">Поиск</a>
          </li>{% comment %}
          <li class="nav-item">
            <a class="nav-link active text-dark" aria-current="page" href="{% url 'category_list' %}">Категории</a>
          </li>{% endcomment %}
          <li class="nav-item">
            <a class="nav-link active text-dark" aria-current="page" href="{% url 'subscription_list' %}">Подписки</a>
          </li>
        </ul>
        {% if request.user.is_authenticated and perms.news.add_post %}
        {% if 'news' in request.get_full_path %}
        <a class="btn btn-success" aria-current="page" href="{% url 'news_create' %}">Добавить новость</a>
        {% elif 'articles' in request.get_full_path %}
        <a class="btn btn-success" aria-current="page" href="{% url 'article_create' %}">Добавить статью</a>
        {% endif %}
        {% endif %}
        {% if user.is_authenticated %}
        <ul class="navbar-nav ms-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#">{{ user.username }}<i
                class="far fa-user"></i></a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'account_logout' %}">Выход</a></li>
            </ul>
          </li>
        </ul>
        {% else %}
        <a class="nav-link" href="{% url 'account_login' %}">Войти</a>
      </div>
      {% endif %}
      {% comment %}
      <form class="d-flex" role="search">
        <div class="input-group">
          <input class="form-control" type="search" placeholder="Поиск" aria-label="Поиск" />
          <button class="input-group-text text-secondary bg-white" type="submit">
            <i class="bi bi-search"></i>
          </button>
        </div>
      </form>
      {% endcomment %}
    </div>
    </div>
  </nav>

  {% block content %}
  {% endblock content %}
  <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
</body>

</html>

templates/pagination.html
{% load search_pagination %}

{% if is_paginated %}
<nav aria-label="Page navigation example" class="align-items-center">
  <ul class="pagination justify-content-center mb-2">
        {% if page_obj.has_previous %}
            <li class="page-item">
              <a class="page-link shadow-none" href="?{% param_replace page=1 %}" tabindex="-1" title="Первая страница">
                  <i class="bi bi-chevron-double-left"></i>
              </a>
            </li>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.paginator.num_pages > 1 %}
                {% if page_obj.number == num %}
                    <li class="page-item active" aria-current="page">
                      <span class="page-link">{{ num }}</span>
                    </li>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <li class="page-item"><a class="page-link shadow-none" href="?{% param_replace page=num %}">{{ num }}</a></li>
                {% endif %}
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link shadow-none" href="?{% param_replace page=paginator.num_pages %}" title="Последняя страница: {{ page_obj.paginator.num_pages }}">
                  <i class="bi bi-chevron-double-right"></i>
              </a>
            </li>
        {% endif %}
  </ul>
</nav>
{% endif %}

templates/post_delete.html
{% extends 'default.html' %}

{% block content %}

<div class="container">
    <div class="text-center"></div>
    <h2>Действительно удалить?</h2>
    <form method="POST">
        {% csrf_token %}
        <hr>
        <button type="submit" class="btn btn-danger">Удалить</button> <button type="button" class="btn btn-primary" onclick="javascript:window.history.back()">Отменить</button>
    </form>
</div>

{% endblock %}

templates/post_detail.html
{%extends 'default.html' %}
{% load custom_filters %}

{% block content %}

<div class="container mt-3">
    <div class="card">
        <h5 class="card-header bg-white text-center">{{ object.title|censor }}</h5>
        <div class="card-body">
            <p class="card-text">{{ object.text|censor }}</p>
            <p class="card-text"><small class="text-muted">{{ object.date_create|date:'d.m.Y' }}</small>
                {% if request.user.is_authenticated and perms.news.add_post %}
                {% if 'news' in request.get_full_path %}
                <a class="btn btn-sm btn-warning" href="{% url 'news_update' object.pk %}"
                    role="button">Редактировать</a>
                <a class="btn btn-sm btn-danger" href="{% url 'news_delete' object.pk %}" role="button">Удалить</a>
                {% elif 'articles' in request.get_full_path %}
                <a class="btn btn-sm btn-warning" href="{% url 'article_update' object.pk %}"
                    role="button">Редактировать</a>
                <a class="btn btn-sm btn-danger" href="{% url 'article_delete' object.pk %}" role="button">Удалить</a>
                {% endif %}
                {% endif %}
            </p>
        </div>
    </div>
</div>

{% endblock content %}

templates/post_form.html
{%extends 'default.html' %}

{% block content %}

<div class="container">
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <button class="btn btn-success mt-2">Добавить</button>
        <button type="button" class="btn btn-primary mt-2" onclick="javascript:window.history.back()">Отменить</button>
    </form>
</div>

{% endblock content %}

templates/post_list.html
{% extends 'default.html' %}
{% load custom_filters %}

{% block content %}

{% if object_list %}
<div class="container my-3">
  <div class="row row-cols-1 row-cols-md-2 g-3">
    {% for obj in object_list %}
    <div class="col">
      <div class="card h-100">
        <div class="card-body">
          <h5 class="card-title">{{ obj.title|censor }}</h5>
          {% if obj.type == 'Новость' %}
          <a class="stretched-link" href="{% url 'news_detail' obj.pk %}"></a>
          {% elif obj.type == 'Статья' %}
          <a class="stretched-link" href="{% url 'article_detail' obj.pk %}"></a>
          {% endif %}
          <p class="card-text">{{ obj.text|censor|truncatechars:20 }}</p>
        </div>
        <div class="card-footer bg-white">
          <small class="text-body-secondary text-muted">{{ obj.type}} {{ obj.date_create|date:'d.m.Y' }}</small>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
<!--- Пагинация  --->
{% include "pagination.html" %}
{% else %}
<h1>новостей нет</h1>
{% endif %}

{% endblock content %}

templates/search.html
{% extends 'default.html' %}
{% load custom_filters %}



{% block content %}    

{%  if object_list %}  
    <div class="container my-3">
        <div class="d-flex justify-content-between align-items-center">               
            <div class="col-auto"> 
                <form method="GET" class="mb-2">
                    <div class="row gx-1 align-items-center justify-content-start">
                        <div class="col-auto">
                            {{ filterset.form.title.label }}:
                        </div>
                        <div class="col-auto">
                            {{ filterset.form.title }}
                        </div>
                        <div class="col-auto">
                            {{ filterset.form.category.label }}:
                        </div>
                        <div class="col-auto">
                            {{ filterset.form.category }}
                        </div>
                        <div class="col-auto">
                            {{ filterset.form.date_create.label }}:
                        </div>
                        <div class="col-auto">
                            {{ filterset.form.date_create }}
                        </div>
                        <div class="col-auto">
                            <button class="btn btn-primary">Найти</button>
                        </div>
                    </div>                    
                </form>    
            </div>           
        </div>
        <div class="row row-cols-1 row-cols-md-2 g-3">
            {% for obj in object_list %}        
                <div class="col">
                    <div class="card h-100">                                  
                        <div class="card-body">
                            <h5 class="card-title">{{ obj.title|censor }}</h5>
                            {% if 'news' in request.get_full_path %}                  
                                <a class="stretched-link" href="{% url 'news_detail' obj.pk %}"></a>
                            {% elif 'articles' in request.get_full_path %}
                                <a class="stretched-link" href="{% url 'article_detail' obj.pk %}"></a>
                            {% endif %}                            
                            <p class="card-text">{{ obj.text|censor|truncatechars:20 }}</p>                            
                        </div>
                        <div class="card-footer bg-white">
                            <small class="text-body-secondary text-muted">{{ obj.type}} {{ obj.date_create|date:'d.m.Y' }}</small>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <!--- Пагинация  --->
    {% include "pagination.html" %}
{%  else %}
    <h1>новостей нет</h1>
{% endif %}

{% endblock content %}

templates/subscription_list.html
{% extends 'default.html' %}

{% block content %}

{% if categories %}
<div class="container my-3">
    <div class="row row-cols-1 row-cols-md-2 g-3">
        {% for obj in categories %}
        <div class="col">
            <div class="card h-100">
                <div class="row align-items-center m-2">
                    <div class="col">
                        <h5 class="">{{ obj.name }}</h5>
                        <a class="" href="#"></a>
                    </div>
                    <div class="col-auto">
                        <form action="{% url 'subscription' obj.id %}" method="POST">
                            {% csrf_token %}
                            {{ form }}
                            {% if obj.name in is_subscriptions %}
                            <button type="submit" name="action" value="unsub"
                                class="btn btn-outline-dark">Отписаться</button>
                            {% else %}
                            <button type="submit" name="action" value="sub"
                                class="btn btn-outline-danger">Подписаться</button>
                            {% endif %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% else %}
<h4 class="text-center mt-3">Подписок нет</h4>
{% endif %}

{% endblock content %}